name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix: # this strategy means, 6jobs will be spawned (using the combinations of configurations given below) from this job definition 
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include: # this configuration will be used once in a job execution
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude: # no job will run with this configuration
                    - node-version: 12
                      operating-system: windows-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build

# The possible combination of configurations include:
# So a job will be spawned for each of these 6configurrations; this is how matrix strategy works;
# Basically, you spin-out multiple job (here, 6jobs) from one job definition as above;
# { node-version: 12, operating-system: ubuntu-latest }
# { node-version: 14, operating-system: ubuntu-latest }
# { node-version: 14, operating-system: windows-latest }
# { node-version: 16, operating-system: windows-latest }
# { node-version: 16, operating-system: windows-latest }
# { node-version: 18, operating-system: ubuntu-latest }
